### PR TITLE
added level8

### PR DESCRIPTION
**Pull request by nightwarrior-xxx**

### CODE REVIEW

**Comment by nightwarrior-xxx** [comment]
Do i need to increase number of directory or i have to increase content in each directory

**Comment by darkHarry** [comment]
Increasing number of directories is mandatory but increasing content(# of files) is optional.
It's up to you if you want to do it.

**Comment by nightwarrior-xxx** [comment]
Is it ok now

**Comment by darkHarry** [comment]
This does what is required but you can still think of a generic extensible approach (i'll leave that to you)
which can be used again for level2.
Few suggestions/changes :
- write well indented code (good practise)
- only create files named `flag` instead of `flag.txt` or `nightwarrior-xxx.txt` or `password.txt`
- rename `osdc_facebook.txt` and `nightwarriorxxx` directories to something more generic.

Thanks.

**Comment by nightwarrior-xxx** [comment]
Also look at level 10 ,we changed it

**Pull request closed without merging**
